#!/bin/sh
g++ -std=c++11 -O3 -flto -march=native -pthread -o wartesystem1 wartesystem.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=1
g++ -std=c++11 -O3 -flto -march=native -pthread -o wartesystem2 wartesystem.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=2
g++ -std=c++11 -O3 -flto -march=native -pthread -o wartesystem4 wartesystem.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=4
g++ -std=c++11 -O3 -flto -march=native -pthread -o wartesystem8 wartesystem.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=8
g++ -std=c++11 -O3 -flto -march=native -pthread -o wartesystem16 wartesystem.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=16
g++ -std=c++11 -O3 -flto -march=native -pthread -o wartesystem32 wartesystem.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=32
g++ -std=c++11 -O3 -flto -march=native -pthread -o wartesystem64 wartesystem.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=64
#
g++ -std=c++11 -O3 -flto -march=native -pthread -o verlustsystem1 verlustsystem.cpp distributedsimulation.cpp erlangb.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=1
g++ -std=c++11 -O3 -flto -march=native -pthread -o verlustsystem2 verlustsystem.cpp distributedsimulation.cpp erlangb.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=2
g++ -std=c++11 -O3 -flto -march=native -pthread -o verlustsystem4 verlustsystem.cpp distributedsimulation.cpp erlangb.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=4
g++ -std=c++11 -O3 -flto -march=native -pthread -o verlustsystem8 verlustsystem.cpp distributedsimulation.cpp erlangb.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=8
g++ -std=c++11 -O3 -flto -march=native -pthread -o verlustsystem16 verlustsystem.cpp distributedsimulation.cpp erlangb.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=16
g++ -std=c++11 -O3 -flto -march=native -pthread -o verlustsystem32 verlustsystem.cpp distributedsimulation.cpp erlangb.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=32
g++ -std=c++11 -O3 -flto -march=native -pthread -o verlustsystem64 verlustsystem.cpp distributedsimulation.cpp erlangb.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=64
#
g++ -std=c++11 -O3 -flto -march=native -pthread -o hybridsystem1 hybridsystem.cpp distributedsimulation.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=1
g++ -std=c++11 -O3 -flto -march=native -pthread -o hybridsystem2 hybridsystem.cpp distributedsimulation.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=2
g++ -std=c++11 -O3 -flto -march=native -pthread -o hybridsystem4 hybridsystem.cpp distributedsimulation.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=4
g++ -std=c++11 -O3 -flto -march=native -pthread -o hybridsystem8 hybridsystem.cpp distributedsimulation.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=8
g++ -std=c++11 -O3 -flto -march=native -pthread -o hybridsystem16 hybridsystem.cpp distributedsimulation.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=16
g++ -std=c++11 -O3 -flto -march=native -pthread -o hybridsystem32 hybridsystem.cpp distributedsimulation.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=32
g++ -std=c++11 -O3 -flto -march=native -pthread -o hybridsystem64 hybridsystem.cpp distributedsimulation.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=64
#
g++ -std=c++11 -O3 -flto -march=native -pthread -o callcenter1 callcenter.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=1
g++ -std=c++11 -O3 -flto -march=native -pthread -o callcenter2 callcenter.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=2
g++ -std=c++11 -O3 -flto -march=native -pthread -o callcenter4 callcenter.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=4
g++ -std=c++11 -O3 -flto -march=native -pthread -o callcenter8 callcenter.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=8
g++ -std=c++11 -O3 -flto -march=native -pthread -o callcenter16 callcenter.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=16
g++ -std=c++11 -O3 -flto -march=native -pthread -o callcenter32 callcenter.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=32
g++ -std=c++11 -O3 -flto -march=native -pthread -o callcenter64 callcenter.cpp distributedsimulation.cpp erlangc.cpp event.cpp eventqueue.cpp packet.cpp packetgenerator.cpp packetqueue.cpp service.cpp simulation.cpp statisticsagent.cpp statisticsaggregate.cpp worker.cpp statisticseventgenerator.cpp -DCORES=64

